[Directory]

path = '/home/tim/shared/'

directory_weights = "weights"
model_segmentation_name = "resnet18"

tsboard = "board"

directory_dataset= "dataset/"

[Segmentation2D]

labels = 'background,flower,peduncle,stem,leaf,fruit'

Sx = 896
Sy = 896 

epochs = 50
batch = 1

learning_rate = 1e-4

[Reconstruction3D]
N_vox = 1000000
coord_file_loc = 'volume/'
